### ISSUE TITLE
neutralizer extension

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/rfc#21]
neutralize the internet
## Phrases
- political corectness === treating people with respect
- hey guys === hey everyone
- boyfriend === partner
- girlfriend === partner
## See Also
- https://whatsortsofpeople.wordpress.com/2008/08/11/ableist-language-alternatives/

**Comment by sindresorhus** [comment]
Relevant:
https://github.com/wooorm/alex
https://github.com/wooorm/retext-equality/blob/master/lib/patterns.json

// @wooorm

**Comment by wooorm** [comment]
:+1:

**Comment by yoshuawuyts** [comment]
Oh hey, totally forgot I thought about this. I'm neck deep into work at the moment, so if anyone wants to take this idea as their own: go for it!
